# Generated by Django 3.0.2 on 2020-01-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45, unique=True)),
                ('email', models.CharField(max_length=45)),
                ('user_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45, unique=True)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=80)),
                ('user_type', models.CharField(max_length=10)),
            ],
        ),
    ]
