# Generated by Django 3.0.2 on 2020-02-04 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200201_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='id',
            new_name='venue_id',
        ),
    ]
