# Generated by Django 3.0.2 on 2020-02-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200204_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='slug',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
