# Generated by Django 3.0.2 on 2020-02-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_venue_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='slug',
            new_name='alt_name',
        ),
    ]
