# Generated by Django 3.0.2 on 2020-02-04 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200204_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='alt_name',
            new_name='slug',
        ),
    ]
